[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Define scheduled function settings
[functions."booking-timeout-handler"]
  schedule = "*/5 * * * *"  # Run every 5 minutes

# Redirects for Netlify functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
